### ISSUE TITLE
Does not run on android - fails on detection

### ISSUE THREAD

**Issue by computerlyrik** [dgomes/openvidonn#5]
Hi, 

i am using a Cyanogenmod based on the latest Android 4 Version.

The app fails as described at the latest comments on google play.
sth like "App crashes on detection"

So i am not alone.
Mine crashes too.

u Need any more information, please tell me.

Oh. latest Vidonn version is according to original app 

PS is there any good opensource sleep tracking software to integrate implement a smart alarm? If anyone knows...it keeps mee vom switching from miband to vidonn.

**Comment by computerlyrik** [comment]
typed from the log on my phone screen:

Cause: NullPointer Exception

RuntimeExceitpon: error receiving broadcast intent { act=com.diogogomes.bluetooth.le.ACTION_GATT_DISCOVERED flg=0x10

Trace to Fragment etc..

Anything meaningful to you?

**Comment by dgomes** [comment]
Sorry :(

Would need full trace back

**Comment by computerlyrik** [comment]
How do i get it from the device into github?

Am 06.07.2015 um 01:21 schrieb Diogo Gomes:

> Sorry :(
> 
> Would need full trace back
> 
> Sent from my mobile device
>

**Comment by dgomes** [comment]
You would need to connect through adb

= Diogo Gomes
http://about.me/dgomes http://about.me/dgomes

**Comment by computerlyrik** [comment]
```
7-06 16:56:07.024  13420-13420/com.diogogomes.openvidonn.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.diogogomes.openvidonn.app, PID: 13420
    java.lang.RuntimeException: Error receiving broadcast Intent { act=com.diogogomes.bluetooth.le.ACTION_GATT_SERVICES_DISCOVERED flg=0x10 } in com.diogogomes.openvidonn.app.CurrentFragment$2@41e52200
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:776)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.diogogomes.openvidonn.app.BluetoothLeService.readVidonnCharacteristic(BluetoothLeService.java:495)
            at com.diogogomes.openvidonn.app.CurrentFragment.updateData(CurrentFragment.java:505)
            at com.diogogomes.openvidonn.app.CurrentFragment$2.onReceive(CurrentFragment.java:262)
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:766)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by computerlyrik** [comment]
Seems like the id is not contained in service Map....

No idea why...

**Comment by computerlyrik** [comment]
So 0000ff01 is not inside the map?

```
characteristic = {String@830034439120} "0000f019-0000-1000-8000-00805f9b34fb"
 value = {char[36]@830034439152} 
 hashCode = 1946794184
 offset = 0
 count = 36
VidonnGattAttributes.VIDONN_SERVICE = {String@830034437840} "0000ff01-0000-1000-8000-00805f9b34fb"
 value = {char[36]@830034437872} 
 hashCode = -1846008105
 offset = 0
 count = 36
mGattCharacteristics = {HashMap@830034424728}  size = 6
 0 = {HashMap$HashMapEntry@830034432696} "0000ffe5-0000-1000-8000-00805f9b34fb" -> " size = 1"
 1 = {HashMap$HashMapEntry@830034427448} "00001801-0000-1000-8000-00805f9b34fb" -> " size = 1"
 2 = {HashMap$HashMapEntry@830034426600} "00001800-0000-1000-8000-00805f9b34fb" -> " size = 3"
 3 = {HashMap$HashMapEntry@830034431848} "0000ffe0-0000-1000-8000-00805f9b34fb" -> " size = 3"
 4 = {HashMap$HashMapEntry@830034429376} "0000180a-0000-1000-8000-00805f9b34fb" -> " size = 4"
 5 = {HashMap$HashMapEntry@830034430224} "0000180f-0000-1000-8000-00805f9b34fb" -> " size = 1"
```

**Comment by computerlyrik** [comment]
Could be useful:

```
7-06 17:19:28.661  26091-26091/com.diogogomes.openvidonn.app D/CurrentFragment﹕ BroadcastReceiver = com.diogogomes.bluetooth.le.ACTION_GATT_CONNECTED
07-06 17:19:28.661  26091-26127/com.diogogomes.openvidonn.app I/BluetoothLeService﹕ Attempting to start service discovery:true
07-06 17:19:28.671  26091-26103/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetService() - Device=CC:7C:F1:0E:F8:CF UUID=00001800-0000-1000-8000-00805f9b34fb
07-06 17:19:28.671  26091-26102/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetService() - Device=CC:7C:F1:0E:F8:CF UUID=00001801-0000-1000-8000-00805f9b34fb
07-06 17:19:28.681  26091-26127/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetService() - Device=CC:7C:F1:0E:F8:CF UUID=0000180a-0000-1000-8000-00805f9b34fb
07-06 17:19:28.681  26091-26103/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetService() - Device=CC:7C:F1:0E:F8:CF UUID=0000180f-0000-1000-8000-00805f9b34fb
07-06 17:19:28.691  26091-26102/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetService() - Device=CC:7C:F1:0E:F8:CF UUID=0000ffe0-0000-1000-8000-00805f9b34fb
07-06 17:19:28.691  26091-26127/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetService() - Device=CC:7C:F1:0E:F8:CF UUID=0000ffe5-0000-1000-8000-00805f9b34fb
07-06 17:19:28.701  26091-26103/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=00002a00-0000-1000-8000-00805f9b34fb
07-06 17:19:28.701  26091-26102/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=00002a01-0000-1000-8000-00805f9b34fb
07-06 17:19:28.721  26091-26127/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=00002a04-0000-1000-8000-00805f9b34fb
07-06 17:19:28.721  26091-26103/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=00002a05-0000-1000-8000-00805f9b34fb
07-06 17:19:28.731  26091-26102/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=00002a29-0000-1000-8000-00805f9b34fb
07-06 17:19:28.731  26091-26127/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=00002a25-0000-1000-8000-00805f9b34fb
07-06 17:19:28.731  26091-26103/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=00002a27-0000-1000-8000-00805f9b34fb
07-06 17:19:28.741  26091-26102/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=00002a28-0000-1000-8000-00805f9b34fb
07-06 17:19:28.741  26091-26127/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=00002a19-0000-1000-8000-00805f9b34fb
07-06 17:19:28.741  26091-26103/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=0000ffe4-0000-1000-8000-00805f9b34fb
07-06 17:19:28.741  26091-26102/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=0000ffe1-0000-1000-8000-00805f9b34fb
07-06 17:19:28.751  26091-26127/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=0000ffe2-0000-1000-8000-00805f9b34fb
07-06 17:19:28.751  26091-26103/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetCharacteristic() - Device=CC:7C:F1:0E:F8:CF UUID=0000ffe9-0000-1000-8000-00805f9b34fb
07-06 17:19:28.751  26091-26102/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetDescriptor() - Device=CC:7C:F1:0E:F8:CF UUID=00002902-0000-1000-8000-00805f9b34fb
07-06 17:19:28.761  26091-26127/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetDescriptor() - Device=CC:7C:F1:0E:F8:CF UUID=00002902-0000-1000-8000-00805f9b34fb
07-06 17:19:28.761  26091-26103/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetDescriptor() - Device=CC:7C:F1:0E:F8:CF UUID=00002902-0000-1000-8000-00805f9b34fb
07-06 17:19:28.761  26091-26102/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onGetDescriptor() - Device=CC:7C:F1:0E:F8:CF UUID=00002902-0000-1000-8000-00805f9b34fb
07-06 17:19:28.761  26091-26127/com.diogogomes.openvidonn.app D/BluetoothGatt﹕ onSearchComplete() = Device=CC:7C:F1:0E:F8:CF Status=0
```

**Comment by dgomes** [comment]
Interesting… are you using the openvidonn X5 or another bracelet ?

= Diogo Gomes
http://about.me/dgomes http://about.me/dgomes

**Comment by computerlyrik** [comment]
Oh yes, it is a X6 model -.-
